// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A smart restock AI agent that suggests optimal reorder quantities for medications.
 *
 * - suggestRestock - A function that suggests optimal reorder quantities based on sales trends and expiration dates.
 * - SuggestRestockInput - The input type for the suggestRestock function.
 * - SuggestRestockOutput - The return type for the suggestRestock function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestRestockInputSchema = z.object({
  salesData: z.string().describe('Historical sales data, as a JSON string.'),
  currentInventory: z.string().describe('Current inventory levels, as a JSON string.'),
  expirationDates: z.string().describe('Expiration dates for each medication, as a JSON string.'),
});
export type SuggestRestockInput = z.infer<typeof SuggestRestockInputSchema>;

const SuggestRestockOutputSchema = z.object({
  suggestedOrders: z.string().describe('Suggested reorder quantities for each medication, as a JSON string.'),
  analysis: z.string().describe('Explanation of why it is suggested to order in the given quantities.'),
});
export type SuggestRestockOutput = z.infer<typeof SuggestRestockOutputSchema>;

export async function suggestRestock(input: SuggestRestockInput): Promise<SuggestRestockOutput> {
  return suggestRestockFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestRestockPrompt',
  input: {schema: SuggestRestockInputSchema},
  output: {schema: SuggestRestockOutputSchema},
  prompt: `You are an expert pharmacy inventory manager. Analyze the provided sales data, current inventory levels, and expiration dates to suggest optimal reorder quantities for each medication. Explain your reasoning.

Sales Data: {{{salesData}}}
Current Inventory: {{{currentInventory}}}
Expiration Dates: {{{expirationDates}}}

Provide the suggested reorder quantities as a JSON string.
Provide the analysis as a string.`,
});

const suggestRestockFlow = ai.defineFlow(
  {
    name: 'suggestRestockFlow',
    inputSchema: SuggestRestockInputSchema,
    outputSchema: SuggestRestockOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
